---
cs_redis_dir: /app/redis
cs_redis_data_dir: "{{ cs_redis_dir }}/data"
cs_redis_certs_dir: "{{ cs_redis_dir }}/certs"
cs_redis_certs_privkey_file: "{{ cs_redis_certs_dir }}/privkey.pem"
cs_redis_certs_cert_file: "{{ cs_redis_certs_dir }}/cert.pem"
cs_redis_certs_chain_file: "{{ cs_redis_certs_dir }}/chain.pem"
cs_redis_cluster_name: blr-home-lab
redis_container_name: redis
redis_docker_image: "docker.io/library/redis"
redis_docker_image_tag: "7.4.1"
