---
- name: Jellyfin | Container | Enable Docker
  ansible.builtin.systemd_service:
      name: docker
      enabled: true
      state: started

- name: Jellyfin | Container | Remove Jellyfin Docker container
  community.docker.docker_container:
      name: "{{ cs_jellyfin_container_name }}"
      state: absent

- name: Jellyfin | Container | Get video group id
  ansible.builtin.getent:
      database: group
      key: video
  register: __jellyfin_video_group

- name: Jellyfin | Container | Get render group id
  ansible.builtin.getent:
      database: group
      key: render
  register: __jellyfin_render_group

- name: Jellyfin | Container | Add Jellyfin to docker group
  ansible.builtin.user:
      name: "{{ cs_jellyfin_user_name }}"
      groups:
          - docker
      append: true

- name: Jellyfin | Container | Get render group id
  ansible.builtin.getent:
      database: passwd
      key: "{{ cs_jellyfin_user_name }}"
  register: __jellyfin_jellyfin_user

- name: Jellyfin | Container | Start Container
  become: true
  become_user: "{{ cs_jellyfin_user_name }}"
  community.docker.docker_container:
      name: "{{ cs_jellyfin_container_name }}"
      image: jellyfin/jellyfin:{{ cs_jellyfin_container_version }}
      state: started
      auto_remove: false
      hostname: "{{ cs_jellyfin_container_name }}"
      detach: true
      privileged: true
      restart_policy: unless-stopped
      # user: "{{ cs_jellyfin_user_name }}:{{ cs_jellyfin_group_name }}"
      user: "{{ __jellyfin_jellyfin_user.ansible_facts.getent_passwd['jellyfin'][1] }}:{{
          __jellyfin_jellyfin_user.ansible_facts.getent_passwd['jellyfin'][2] }}"
      devices: "{{ cs_jellyfin_container_dri_list }}"
      env_file: "{{ cs_jellyfin_config_dir }}/env"
      groups:
          - "{{ __jellyfin_video_group.ansible_facts.getent_group['video'][1] }}"
          - "{{ __jellyfin_render_group.ansible_facts.getent_group['render'][1] }}"
      ports:
          - "{{ cs_jellyfin_internal_http_port }}:{{ cs_jellyfin_internal_http_port }}"
          - "{{ cs_jellyfin_internal_https_port }}:{{ cs_jellyfin_internal_https_port }}"
          - "{{ cs_jellyfin_public_http_port }}:{{ cs_jellyfin_public_http_port }}"
          - "{{ cs_jellyfin_public_https_port }}:{{ cs_jellyfin_public_https_port }}"
          - "8096:8096"
          - "7359:7359"
          - "1900:1900"
      volumes:
          - "{{ cs_jellyfin_media_dir }}:{{ cs_jellyfin_media_dir }}"
          - "{{ cs_jellyfin_data_dir }}:{{ cs_jellyfin_data_dir }}"
          - "{{ cs_jellyfin_config_dir }}:{{ cs_jellyfin_config_dir }}"
          - "{{ cs_jellyfin_log_dir }}:{{ cs_jellyfin_log_dir }}"
          - "{{ cs_jellyfin_cache_dir }}:{{ cs_jellyfin_cache_dir }}"
      mounts:
          - source: "{{ cs_jellyfin_media_dir }}"
            target: "/media"
            type: bind
            read_only: false
      env:
          TZ: Asia/Kolkata
