---
cs_elasticsearch_docker_container_name: elasticsearch
cs_elasticsearch_docker_image: docker.io/nextcloud/aio-fulltextsearch
cs_elasticsearch_docker_image_tag: latest
cs_elasticsearch_cluster_name: blr-home-lab
cs_elasticsearch_run_user_id: 1000
cs_elasticsearch_run_group_id: 0
cs_elasticsearch_dir: /app/elasticsearch
cs_elasticsearch_data_dir: "{{ cs_elasticsearch_dir }}/data"
